//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTracking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int numero { get; set; }
        public int TrackingId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string detalle1 { get; set; }
    
        public virtual Tracking Tracking { get; set; }
    }
}
